---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: hello-jkube
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.github.gscordeiro
    app.kubernetes.io/part-of: com.github.gscordeiro
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: hello-jkube
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: hello-jkube
data:
  hello.msg: Hello Ambiente DEV
