---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.eclipse.org/git-commit: 5bbf68d03f4b2a6f4536d939837494ec3ede47c6
    jkube.eclipse.org/git-url: https://bitbucket.org/gilliard/hello-jkube.git
    jkube.eclipse.org/git-branch: main
  labels:
    app: hello-jkube
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.github.gscordeiro
    app.kubernetes.io/part-of: com.github.gscordeiro
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: hello-jkube
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: hello-jkube
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-jkube
      provider: jkube
      group: com.github.gscordeiro
      app.kubernetes.io/name: hello-jkube
      app.kubernetes.io/part-of: com.github.gscordeiro
      app.kubernetes.io/managed-by: jkube
  template:
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: 5bbf68d03f4b2a6f4536d939837494ec3ede47c6
        jkube.eclipse.org/git-url: https://bitbucket.org/gilliard/hello-jkube.git
        jkube.eclipse.org/git-branch: main
      labels:
        app: hello-jkube
        provider: jkube
        version: 1.0.0-SNAPSHOT
        group: com.github.gscordeiro
        app.kubernetes.io/part-of: com.github.gscordeiro
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: hello-jkube
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: HELLO_MSG
          value: Mensagem estatica
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: gscordeiro/hello-jkube:latest
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
